version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ps-emakers
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver

  db:
    image: postgres:15
    container_name: postgres_biblioteca
    restart: always
    environment:
      POSTGRES_DB: ps-emakers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data