CREATE SEQUENCE IF NOT EXISTS emprestimo_id_emprestimo_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS livro_id_livro_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS pessoa_id_pessoa_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE emprestimo
(
    id_emprestimo   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_emprestimo date                                    NOT NULL,
    situacao        VARCHAR(255)                            NOT NULL,
    id_livro        BIGINT                                  NOT NULL,
    id_pessoa       BIGINT                                  NOT NULL,
    CONSTRAINT emprestimo_pkey PRIMARY KEY (id_emprestimo)
);

CREATE TABLE livro
(
    id_livro        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    autor           VARCHAR(100)                            NOT NULL,
    data_lancamento date                                    NOT NULL,
    nome            VARCHAR(100)                            NOT NULL,
    CONSTRAINT livro_pkey PRIMARY KEY (id_livro)
);

CREATE TABLE pessoa
(
    id_pessoa   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cep         VARCHAR(9)                              NOT NULL,
    cpf         VARCHAR(14)                             NOT NULL,
    email       VARCHAR(100)                            NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    senha       VARCHAR(100)                            NOT NULL,
    CONSTRAINT pessoa_pkey PRIMARY KEY (id_pessoa)
);

ALTER TABLE emprestimo
    ADD CONSTRAINT fk9o80s7i3wn6ks727ytgmudti4 FOREIGN KEY (id_livro) REFERENCES livro (id_livro) ON DELETE NO ACTION;

ALTER TABLE emprestimo
    ADD CONSTRAINT fkeujhum1ufew05uykqc54c9dg FOREIGN KEY (id_pessoa) REFERENCES pessoa (id_pessoa) ON DELETE NO ACTION;